/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import login.loginForm;

/**
 *
 * @author Ilham Maulana
 */
public class Operator extends javax.swing.JFrame {

    /**
     * Creates new form Operator
     */
    Color defaultColor, clickedColor, penDefault, penEnter, penClick, fontColorClicked,fontColorDefault;
    public Operator() {
        initComponents();
        defaultColor = new Color(34,47,63);
        clickedColor = new Color(57, 70, 86);
      
        penDefault = new Color(153,153,153);
        fontColorDefault = new Color(255,255,255);
        penEnter = new Color(204,204,204);
        fontColorClicked = new Color(255,255,255);
        penClick = new Color(52, 132, 103);
        
        jPanelLogout.setBackground(penDefault);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        menuStok = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        kelolaJenis = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        jPanelLogout = new javax.swing.JPanel();
        textLogout = new javax.swing.JLabel();
        menuDashboard = new javax.swing.JPanel();
        label_2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_3 = new javax.swing.JLabel();
        titleDashboard = new javax.swing.JLabel();
        kelolaBarang = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(34, 47, 63));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuStok.setBackground(new java.awt.Color(34, 47, 63));
        menuStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuStokMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuStokMousePressed(evt);
            }
        });

        label3.setBackground(new java.awt.Color(13, 36, 51));
        label3.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/daftar.png"))); // NOI18N
        label3.setText("Daftar Calon Peserta Didik");

        javax.swing.GroupLayout menuStokLayout = new javax.swing.GroupLayout(menuStok);
        menuStok.setLayout(menuStokLayout);
        menuStokLayout.setHorizontalGroup(
            menuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuStokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuStokLayout.setVerticalGroup(
            menuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel13.add(menuStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 320, 60));

        kelolaJenis.setBackground(new java.awt.Color(34, 47, 63));
        kelolaJenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelolaJenisMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kelolaJenisMousePressed(evt);
            }
        });

        label8.setBackground(new java.awt.Color(13, 36, 51));
        label8.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ceklis.png"))); // NOI18N
        label8.setText("Daftar Siswa Lolos Seleksi");

        javax.swing.GroupLayout kelolaJenisLayout = new javax.swing.GroupLayout(kelolaJenis);
        kelolaJenis.setLayout(kelolaJenisLayout);
        kelolaJenisLayout.setHorizontalGroup(
            kelolaJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelolaJenisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        kelolaJenisLayout.setVerticalGroup(
            kelolaJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel13.add(kelolaJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 320, 60));

        jPanelLogout.setBackground(new java.awt.Color(79, 90, 104));
        jPanelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelLogoutMouseReleased(evt);
            }
        });

        textLogout.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        textLogout.setForeground(new java.awt.Color(255, 255, 255));
        textLogout.setText("LOGOUT");

        javax.swing.GroupLayout jPanelLogoutLayout = new javax.swing.GroupLayout(jPanelLogout);
        jPanelLogout.setLayout(jPanelLogoutLayout);
        jPanelLogoutLayout.setHorizontalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoutLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(textLogout)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanelLogoutLayout.setVerticalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.add(jPanelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 230, -1));

        menuDashboard.setBackground(new java.awt.Color(34, 47, 63));
        menuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashboardMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuDashboardMousePressed(evt);
            }
        });

        label_2.setBackground(new java.awt.Color(13, 36, 51));
        label_2.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        label_2.setForeground(new java.awt.Color(255, 255, 255));
        label_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboardSD.png"))); // NOI18N
        label_2.setText("Dashboard");

        javax.swing.GroupLayout menuDashboardLayout = new javax.swing.GroupLayout(menuDashboard);
        menuDashboard.setLayout(menuDashboardLayout);
        menuDashboardLayout.setHorizontalGroup(
            menuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuDashboardLayout.setVerticalGroup(
            menuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDashboardLayout.createSequentialGroup()
                .addComponent(label_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel13.add(menuDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 320, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/100.png"))); // NOI18N
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 90));

        label_3.setBackground(new java.awt.Color(13, 36, 51));
        label_3.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        label_3.setForeground(new java.awt.Color(255, 255, 255));
        label_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel13.add(label_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 90, 230, 30));

        titleDashboard.setBackground(new java.awt.Color(13, 36, 51));
        titleDashboard.setFont(new java.awt.Font(".SF NS Text", 1, 24)); // NOI18N
        titleDashboard.setForeground(new java.awt.Color(255, 255, 255));
        titleDashboard.setText("PPDB");
        jPanel13.add(titleDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 100, 34));

        kelolaBarang.setBackground(new java.awt.Color(34, 47, 63));
        kelolaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelolaBarangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kelolaBarangMousePressed(evt);
            }
        });

        label4.setBackground(new java.awt.Color(13, 36, 51));
        label4.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tambah.png"))); // NOI18N
        label4.setText("Form Pendaftaran Peserta");

        javax.swing.GroupLayout kelolaBarangLayout = new javax.swing.GroupLayout(kelolaBarang);
        kelolaBarang.setLayout(kelolaBarangLayout);
        kelolaBarangLayout.setHorizontalGroup(
            kelolaBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelolaBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        kelolaBarangLayout.setVerticalGroup(
            kelolaBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel13.add(kelolaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 320, 60));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 770));

        navbar.setBackground(new java.awt.Color(34, 47, 63));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hallo, Dedi Supriadi");
        navbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, 50));
        navbar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        navbar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        jPanel12.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1050, 50));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1050, 720));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPanel12.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 1050, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStokMouseClicked
        DaftarCalonSiswa frame = new DaftarCalonSiswa();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frame).setVisible(true);
    }//GEN-LAST:event_menuStokMouseClicked

    private void menuStokMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStokMousePressed
        // TODO add your handling code here:

        menuStok.setBackground(clickedColor);
        kelolaBarang.setBackground(defaultColor);
        kelolaJenis.setBackground(defaultColor);
        menuDashboard.setBackground(defaultColor);
    }//GEN-LAST:event_menuStokMousePressed

    private void kelolaJenisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelolaJenisMouseClicked
        DaftarSiswaLolosSeleksi frmMasterSatuan = new DaftarSiswaLolosSeleksi();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmMasterSatuan).setVisible(true);
    }//GEN-LAST:event_kelolaJenisMouseClicked

    private void kelolaJenisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelolaJenisMousePressed
        // TODO add your handling code here:

        menuStok.setBackground(defaultColor);
        kelolaBarang.setBackground(defaultColor);
        kelolaJenis.setBackground(clickedColor);
        menuDashboard.setBackground(defaultColor);

    }//GEN-LAST:event_kelolaJenisMousePressed

    private void jPanelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMouseClicked

        loginForm login = new loginForm();
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("images/logout.png"));
        int pilih = JOptionPane.showConfirmDialog(null, "Yakin ingin keluar?" ,"Logout",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (pilih == JOptionPane.OK_OPTION){
            login.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame();
        }
    }//GEN-LAST:event_jPanelLogoutMouseClicked

    private void jPanelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMouseEntered
        jPanelLogout.setBackground(penEnter);
        textLogout.setForeground(fontColorDefault);
    }//GEN-LAST:event_jPanelLogoutMouseEntered

    private void jPanelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMouseExited
        jPanelLogout.setBackground(penDefault);
        textLogout.setForeground(fontColorDefault);
    }//GEN-LAST:event_jPanelLogoutMouseExited

    private void jPanelLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMousePressed
        jPanelLogout.setBackground(penDefault);
        textLogout.setForeground(fontColorDefault);
    }//GEN-LAST:event_jPanelLogoutMousePressed

    private void jPanelLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMouseReleased
        jPanelLogout.setBackground(penDefault);
        textLogout.setForeground(fontColorDefault);
    }//GEN-LAST:event_jPanelLogoutMouseReleased

    private void menuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMouseClicked
        DashboardPegawaiFrame frame = new DashboardPegawaiFrame();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frame).setVisible(true);
    }//GEN-LAST:event_menuDashboardMouseClicked

    private void menuDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMousePressed
        menuDashboard.setBackground(clickedColor);
        kelolaBarang.setBackground(defaultColor);
        menuStok.setBackground(defaultColor);
        kelolaJenis.setBackground(defaultColor);
    }//GEN-LAST:event_menuDashboardMousePressed

    private void kelolaBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelolaBarangMouseClicked
        // TODO add your handling code here:
        FormDaftarPesertaDidik frmMasterBarang = new FormDaftarPesertaDidik();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmMasterBarang).setVisible(true);

    }//GEN-LAST:event_kelolaBarangMouseClicked

    private void kelolaBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelolaBarangMousePressed
        // TODO add your handling code here:

        menuStok.setBackground(defaultColor);
        kelolaBarang.setBackground(clickedColor);
        kelolaJenis.setBackground(defaultColor);
        menuDashboard.setBackground(defaultColor);

    }//GEN-LAST:event_kelolaBarangMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("images/250.png"));
   setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanelLogout;
    private javax.swing.JPanel kelolaBarang;
    private javax.swing.JPanel kelolaJenis;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label_2;
    private javax.swing.JLabel label_3;
    private javax.swing.JPanel menuDashboard;
    private javax.swing.JPanel menuStok;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel textLogout;
    private javax.swing.JLabel titleDashboard;
    // End of variables declaration//GEN-END:variables
}
